# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fePnbiVQES0QlSKFA9B7g0clpMki2PXY
"""

!pip install streamlit
import streamlit as st
import joblib
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# =========================
# STREAMLIT CONFIG
# =========================
st.set_page_config(
    page_title="Cyberbullying Detection System",
    page_icon="🧑‍💻",
    layout="wide"
)

# =========================
# CUSTOM CSS
# =========================
st.markdown("""
<style>
/* Background utama */
.stApp {
    background-color: #0e1117;
    border: 4px solid #7c3aed;
}

/* Hilangkan padding default */
.block-container {
    padding-top: 100px;
    padding-left: 220px;
    padding-right: 220px;
}

/* Container utama */
.main-box {
    max-width: 760px;
    margin: auto;
}

/* Header */
.header {
    display: flex;
    align-items: center;
    gap: 18px;
    margin-bottom: 35px;
}

.logo-box {
    width: 42px;
    height: 42px;
    background-color: white;
    border-radius: 4px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 24px;
}

.title-text {
    color: #ffffff;
    font-size: 34px;
    font-weight: 800;
    margin: 0;
}

/* Label input */
.input-label {
    color: #ffffff;
    font-size: 13px;
    font-weight: 600;
    margin-bottom: 8px;
}

/* Text area */
textarea {
    background-color: #ffffff !important;
    color: #111827 !important;
    border-radius: 6px !important;
    border: none !important;
    font-size: 15px !important;
}

/* Tombol */
.stButton > button {
    background-color: #4f46e5;
    color: white;
    border: none;
    border-radius: 5px;
    padding: 8px 22px;
    font-size: 13px;
    font-weight: 700;
}

.stButton > button:hover {
    background-color: #4338ca;
    color: white;
    border: none;
}

/* Hasil prediksi */
.result-box {
    margin-top: 25px;
    padding: 18px;
    background-color: #111827;
    border: 1px solid #7c3aed;
    border-radius: 8px;
    color: white;
}

.result-title {
    font-size: 18px;
    font-weight: 700;
    margin-bottom: 8px;
}

.result-label {
    font-size: 22px;
    font-weight: 800;
    color: #a78bfa;
}
</style>
""", unsafe_allow_html=True)


# =========================
# LOAD NLTK
# =========================
try:
    nltk.data.find("tokenizers/punkt")
except LookupError:
    nltk.download("punkt")

try:
    nltk.data.find("corpora/stopwords")
except LookupError:
    nltk.download("stopwords")


# =========================
# LOAD MODEL
# =========================
@st.cache_resource
def load_assets():
    vectorizer = joblib.load("tfidf_vectorizer.pkl")
    encoder = joblib.load("label_encoder.pkl")
    model = joblib.load("best_model.pkl")
    return vectorizer, encoder, model

tfidf_vectorizer, label_encoder, model = load_assets()


# =========================
# PREPROCESSING
# =========================
stop_words = set(stopwords.words("english"))
stemmer = PorterStemmer()

def clean_text(text):
    if not isinstance(text, str):
        return ""

    text = text.lower()
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)
    text = re.sub(r"@\w+|#\w+", "", text)
    text = text.encode("ascii", "ignore").decode()
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    words = nltk.word_tokenize(text)
    words = [word for word in words if word not in stop_words and len(word) > 2]
    words = [stemmer.stem(word) for word in words]

    return " ".join(words)


# =========================
# UI
# =========================
st.markdown('<div class="main-box">', unsafe_allow_html=True)

st.markdown("""
<div class="header">
    <div class="logo-box">🧑‍💻</div>
    <h1 class="title-text">Cyberbullying Detection System</h1>
</div>
""", unsafe_allow_html=True)

st.markdown('<div class="input-label">Masukkan komentar atau teks:</div>', unsafe_allow_html=True)

input_text = st.text_area(
    label="",
    height=95,
    label_visibility="collapsed"
)

predict_button = st.button("Prediksi")

if predict_button:
    if input_text.strip() == "":
        st.warning("Masukkan teks terlebih dahulu.")
    else:
        cleaned_text = clean_text(input_text)
        vectorized_text = tfidf_vectorizer.transform([cleaned_text])
        prediction = model.predict(vectorized_text)[0]

        predicted_label = label_encoder.inverse_transform([prediction])[0]

        st.markdown(f"""
        <div class="result-box">
            <div class="result-title">Hasil Prediksi</div>
            <div class="result-label">{predicted_label}</div>
        </div>
        """, unsafe_allow_html=True)

st.markdown('</div>', unsafe_allow_html=True)
